### ISSUE TITLE
[DOC] https://rapids.ai/documentation.html does not need to gunzip data for cuML examples

### ISSUE THREAD

**Issue by tym1062** [rapidsai/demos#11]
The _gunzip_ step included in RAPIDS documentation is not necessary:

**/rapids/notebooks/cuml - cuML demo notebooks**
These notebooks have data pre-loaded in the container image and requires the following command to be run for decompression: _cd /rapids/notebooks/cuml/data && gunzip mortgage.npy.gz_

If the _gunzip_ step is performed, the notebook will use random data, and not read from the mortgage data.

Code in the cuML notebooks will automatically unzip the mortgage file using _gzip.open_ method:

    if os.path.exists(cached) and source=='mortgage':
        print('use mortgage data')
        with gzip.open(cached) as f:
            X = np.load(f)
        X = X[np.random.randint(0,X.shape[0]-1,nrows),:ncols]

**Comment by mike-wendt** [comment]
Fixed on site and in docs, thanks for the issue
