### ISSUE TITLE
[BUG] start-jupyter.sh: line 5: jupyter-lab: command not found

### ISSUE THREAD

**Issue by ahehn-nv** [rapidsai/demos#13]
Following https://rapids.ai/start.html#docker-container, the execution of
```
bash utils/start-jupyter.sh
```
in the rapidsai:latest docker container (image id: 9058fbba969c)
fails with
```
start-jupyter.sh: line 5: jupyter-lab: command not found
```

Fix: The script works if you add `/conda/envs/rapids/bin/` to the PATH environment variable.

**Comment by mike-wendt** [comment]
Working on a fix now

**Comment by mike-wendt** [comment]
New containers pushed, please pull and retry. Close if issue is resolved @ahehn-nv

**Comment by ahehn-nv** [comment]
It works now. Thanks for fixing!
